### ISSUE TITLE
submission entries with missing references

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/catalog#111]
Links to submisions with missing references. they need to be added to zotero and then linked to in the submissions

### lower trophic

- [ ] [mesozoo](https://github.com/NOAA-EDAB/catalog/issues/79)
- [x] [habs](https://github.com/NOAA-EDAB/catalog/issues/45)

### megafauna

- [x] [survey impacts](https://github.com/NOAA-EDAB/catalog/issues/106)
- [x] [spawn timing](https://github.com/NOAA-EDAB/catalog/issues/87)
- [x] [productivity anomaly](https://github.com/NOAA-EDAB/catalog/issues/60)
- [x] [gray seal](https://github.com/NOAA-EDAB/catalog/issues/41)
- [x] [salmon](https://github.com/NOAA-EDAB/catalog/issues/65)
- [x] [feeding guilds](https://github.com/NOAA-EDAB/catalog/issues/85)

### oceanographic and habitat

- [x] [bottom temp seasonal](https://github.com/NOAA-EDAB/catalog/issues/51)
- [x] [gulf stream index](https://github.com/NOAA-EDAB/catalog/issues/40)
- [x] [slopewater](https://github.com/NOAA-EDAB/catalog/issues/46)
- [x] [heatwave intensity](https://github.com/NOAA-EDAB/catalog/issues/72)
- [x] [heatwave events](https://github.com/NOAA-EDAB/catalog/issues/82)
- [x] [timing shift risks](https://github.com/NOAA-EDAB/catalog/issues/99)
- [x] [ocean acidification](https://github.com/NOAA-EDAB/catalog/issues/67)

### economic and social

- [x] [bennet](https://github.com/NOAA-EDAB/catalog/issues/74)

- [x] [glossary](https://noaa-edab.github.io/catalog/state-of-the-ecosystem-plain-language-glossary.html)

**Comment by andybeet** [comment]
@BBeltz1 When you get a reply from J. Runge can you add the references to [this](https://github.com/NOAA-EDAB/catalog/issues/79) issue? thanks
